# Generated by Django 5.2.6 on 2025-10-16 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccines', '0024_vaccine_low_stock_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineStockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100, verbose_name='Số lô')),
                ('expiry_date', models.DateField(verbose_name='Hạn dùng')),
                ('quantity_total', models.PositiveIntegerField(default=0, verbose_name='Tổng số lượng')),
                ('quantity_available', models.PositiveIntegerField(default=0, verbose_name='Số lượng khả dụng')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kho/cơ sở')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_lots', to='vaccines.vaccine', verbose_name='Vắc xin')),
            ],
            options={
                'verbose_name': 'Lô vắc xin',
                'verbose_name_plural': 'Danh sách lô vắc xin',
            },
        ),
        migrations.CreateModel(
            name='BookingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('reserved', 'Đã giữ chỗ'), ('consumed', 'Đã tiêu thụ'), ('released', 'Đã trả lại')], default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('booking_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='vaccines.bookingitem')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='inventory.vaccinestocklot')),
            ],
        ),
        migrations.AddIndex(
            model_name='vaccinestocklot',
            index=models.Index(fields=['vaccine', 'expiry_date', 'is_active'], name='inventory_v_vaccine_07e207_idx'),
        ),
    ]
