# Generated by Django 5.2.6 on 2025-10-28 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_point_fk_to_records_state'),
        ('vaccines', '0027_remove_booking_stubs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingallocation',
            options={'ordering': ['-reserved_at'], 'verbose_name': 'Phân bổ lịch hẹn', 'verbose_name_plural': 'Phân bổ lịch hẹn'},
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('desired_qty', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số lượng mong muốn')),
                ('urgency', models.CharField(choices=[('low', 'Nhẹ'), ('normal', 'Thường'), ('high', 'Khẩn')], default='normal', max_length=10, verbose_name='Mức độ')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('ack', 'Đã tiếp nhận'), ('done', 'Đã xử lý')], default='new', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm tạo')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Tiếp nhận lúc')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Xử lý lúc')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_inventory_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
                ('vaccine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_alerts', to='vaccines.vaccine', verbose_name='Vắc xin')),
            ],
            options={
                'verbose_name': 'Thông báo tồn kho',
                'verbose_name_plural': 'Thông báo tồn kho',
                'ordering': ['-created_at'],
            },
        ),
    ]
