# Generated by Django 5.2.6 on 2025-11-23 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_bookingallocation_options_inventoryalert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryAlert',
        ),
    ]
