# Generated by Django 5.2.6 on 2025-10-05 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner quảng cáo', 'verbose_name_plural': 'Danh sách banner quảng cáo'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Lịch hẹn tiêm', 'verbose_name_plural': 'Danh sách lịch hẹn tiêm'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Bệnh', 'verbose_name_plural': 'Danh sách bệnh'},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'verbose_name': 'Vắc xin', 'verbose_name_plural': 'Danh sách vắc xin'},
        ),
        migrations.AlterModelOptions(
            name='vaccinecategory',
            options={'verbose_name': 'Danh mục vắc xin', 'verbose_name_plural': 'Danh sách danh mục vắc xin'},
        ),
        migrations.AlterModelOptions(
            name='vaccinepackage',
            options={'verbose_name': 'Gói tiêm chủng', 'verbose_name_plural': 'Danh sách gói tiêm chủng'},
        ),
        migrations.RemoveField(
            model_name='banner',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='note',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='complications',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='vaccinecategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='vaccinepackage',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Liên kết'),
        ),
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Trạng thái hiển thị'),
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hẹn tiêm'),
        ),
        migrations.AddField(
            model_name='booking',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ hẹn tiêm'),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm tiêm'),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú thêm'),
        ),
        migrations.AddField(
            model_name='disease',
            name='cause',
            field=models.TextField(blank=True, null=True, verbose_name='Nguyên nhân'),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention',
            field=models.TextField(blank=True, null=True, verbose_name='Phòng ngừa'),
        ),
        migrations.AddField(
            model_name='disease',
            name='status',
            field=models.CharField(choices=[('active', 'Đang hoạt động'), ('inactive', 'Ngừng hoạt động')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptom',
            field=models.TextField(blank=True, null=True, verbose_name='Triệu chứng'),
        ),
        migrations.AddField(
            model_name='vaccinecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AddField(
            model_name='vaccinecategory',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Trạng thái hiển thị'),
        ),
        migrations.AddField(
            model_name='vaccinepackage',
            name='status',
            field=models.CharField(choices=[('active', 'Còn hiệu lực'), ('inactive', 'Ngừng cung cấp')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='vaccinepackage',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tổng giá tiền'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='Hình ảnh'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaccines.vaccinepackage', verbose_name='Gói tiêm'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('completed', 'Đã tiêm xong'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái lịch hẹn'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đặt'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaccines.vaccine', verbose_name='Vắc xin'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả bệnh'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên bệnh'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='age_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Độ tuổi áp dụng'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày phê duyệt'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccines', to='vaccines.vaccinecategory', verbose_name='Danh mục vắc xin'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='contraindications',
            field=models.TextField(blank=True, null=True, verbose_name='Chống chỉ định'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='vaccines.disease', verbose_name='Bệnh phòng ngừa'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='doses_required',
            field=models.IntegerField(default=1, verbose_name='Số liều cần tiêm'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vaccines/', verbose_name='Hình ảnh minh họa'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='indications',
            field=models.TextField(blank=True, null=True, verbose_name='Chỉ định'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='interval_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Khoảng cách giữa các liều (ngày)'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhà sản xuất'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên vắc xin'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Xuất xứ'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Giá tiền'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='side_effects',
            field=models.TextField(blank=True, null=True, verbose_name='Tác dụng phụ'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='status',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Ngừng hoạt động')], default='active', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='storage_requirements',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Điều kiện bảo quản'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Loại vắc xin'),
        ),
        migrations.AlterField(
            model_name='vaccinecategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='vaccinepackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='vaccinepackage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả gói tiêm'),
        ),
        migrations.AlterField(
            model_name='vaccinepackage',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Giảm giá (%)'),
        ),
        migrations.AlterField(
            model_name='vaccinepackage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên gói tiêm'),
        ),
        migrations.AlterField(
            model_name='vaccinepackage',
            name='vaccines',
            field=models.ManyToManyField(related_name='packages', to='vaccines.vaccine', verbose_name='Danh sách vắc xin'),
        ),
    ]
