# Generated by Django 5.2.6 on 2025-10-05 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_alter_banner_options_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='approval_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Ngày phê duyệt'),
        ),
    ]
