# Generated by Django 5.2.6 on 2025-10-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0003_alter_vaccine_approval_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='doses_required',
            field=models.IntegerField(default=1, verbose_name='Phác đồ điều trị'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vaccines/', verbose_name='Hình ảnh '),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='interval_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Khoảng cách giữa các mũi tiêm (ngày)'),
        ),
    ]
