# Generated by Django 5.2.6 on 2025-10-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0004_alter_vaccine_doses_required_alter_vaccine_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='unit',
            field=models.CharField(default='liều', max_length=50, verbose_name='Đơn vị tính'),
        ),
    ]
