# Generated by Django 5.2.6 on 2025-10-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0005_vaccine_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vaccine_categories/', verbose_name='Hình ảnh danh mục'),
        ),
    ]
