# Generated by Django 5.2.6 on 2025-10-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0006_vaccinecategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='unit',
            field=models.CharField(choices=[('liều', 'Liều'), ('chai', 'Chai'), ('lọ', 'Lọ'), ('hộp', 'Hộp')], default='liều', max_length=50, verbose_name='Đơn vị tính'),
        ),
    ]
