# Generated by Django 5.2.6 on 2025-10-06 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0007_alter_vaccine_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinePackageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên nhóm gói (VD: 6 gói theo độ tuổi)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả nhóm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('status', models.BooleanField(default=True, verbose_name='Hiển thị')),
            ],
            options={
                'verbose_name': 'Nhóm gói tiêm',
                'verbose_name_plural': 'Danh sách nhóm gói tiêm',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='vaccinepackage',
            options={'verbose_name': 'Gói vắc xin', 'verbose_name_plural': 'Danh sách gói vắc xin'},
        ),
        migrations.RemoveField(
            model_name='vaccinepackage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vaccinepackage',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='vaccinepackage',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='vaccinepackage',
            name='vaccines',
        ),
        migrations.AlterField(
            model_name='vaccinepackage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='vaccinepackage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên gói vắc xin'),
        ),
        migrations.AlterField(
            model_name='vaccinepackage',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.CreateModel(
            name='VaccinePackageDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_diseases', to='vaccines.disease')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_groups', to='vaccines.vaccinepackage')),
                ('vaccines', models.ManyToManyField(related_name='package_disease_vaccines', to='vaccines.vaccine', verbose_name='Danh sách vắc xin cho bệnh này')),
            ],
            options={
                'verbose_name': 'Bệnh trong gói tiêm',
                'verbose_name_plural': 'Danh sách bệnh trong gói tiêm',
            },
        ),
        migrations.AddField(
            model_name='vaccinepackage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='vaccines.vaccinepackagegroup', verbose_name='Thuộc nhóm gói'),
        ),
    ]
