# Generated by Django 5.2.6 on 2025-10-06 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0008_vaccinepackagegroup_alter_vaccinepackage_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
