# Generated by Django 5.2.6 on 2025-10-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0009_delete_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinepackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
    ]
