# Generated by Django 5.2.6 on 2025-10-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0010_vaccinepackage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lịch hẹn tiêm', 'verbose_name_plural': 'Danh sách lịch hẹn tiêm'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bệnh', 'verbose_name_plural': 'Danh sách bệnh'},
        ),
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vắc xin', 'verbose_name_plural': 'Danh sách vắc xin'},
        ),
        migrations.AlterModelOptions(
            name='vaccinecategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Danh mục vắc xin', 'verbose_name_plural': 'Danh sách danh mục vắc xin'},
        ),
        migrations.AlterModelOptions(
            name='vaccinepackage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Gói vắc xin', 'verbose_name_plural': 'Danh sách gói vắc xin'},
        ),
        migrations.AlterModelOptions(
            name='vaccinepackagegroup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Nhóm gói tiêm', 'verbose_name_plural': 'Danh sách nhóm gói tiêm'},
        ),
        migrations.AddField(
            model_name='vaccinecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='vaccinepackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='vaccinepackagegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
    ]
