# Generated by Django 5.2.6 on 2025-10-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0011_alter_booking_options_alter_disease_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='age_group',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='age_unit',
            field=models.CharField(choices=[('tuổi', 'Tuổi'), ('tháng', 'Tháng')], default='tuổi', max_length=10, verbose_name='Đơn vị tuổi'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='max_age',
            field=models.IntegerField(blank=True, help_text='Ví dụ: 5 hoặc 12', null=True, verbose_name='Tuổi lớn nhất'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='min_age',
            field=models.IntegerField(blank=True, help_text='Ví dụ: 0 hoặc 2', null=True, verbose_name='Tuổi nhỏ nhất'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='schedule_text',
            field=models.TextField(blank=True, help_text='Ví dụ: Trẻ từ 2 tuổi trở lên tiêm 1 liều cơ bản, nhắc lại sau 5 năm...', null=True, verbose_name='Phác đồ lịch tiêm'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Loại vắc xin'),
        ),
    ]
