# Generated by Django 5.2.6 on 2025-10-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0012_remove_vaccine_age_group_vaccine_age_unit_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vaccine',
            index=models.Index(fields=['status', 'age_unit', 'min_age', 'max_age', 'disease'], name='vaccines_va_status_22415e_idx'),
        ),
    ]
