# Generated by Django 5.2.6 on 2025-10-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0013_vaccine_vaccines_va_status_22415e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='max_age',
            field=models.IntegerField(blank=True, help_text='VD: 5 hoặc 12', null=True, verbose_name='Tuổi lớn nhất'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='min_age',
            field=models.IntegerField(blank=True, help_text='VD: 0 hoặc 2', null=True, verbose_name='Tuổi nhỏ nhất'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='schedule_text',
            field=models.TextField(blank=True, help_text='VD: Trẻ từ 2 tuổi trở lên tiêm 1 liều cơ bản, nhắc lại sau 5 năm...', null=True, verbose_name='Phác đồ lịch tiêm'),
        ),
    ]
