# Generated by Django 5.2.6 on 2025-10-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0014_alter_vaccine_max_age_alter_vaccine_min_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='vaccinepackagegroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
