# Generated by Django 5.2.6 on 2025-10-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0015_vaccine_slug_vaccinepackagegroup_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinepackagedisease',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
