# Generated by Django 5.2.6 on 2025-10-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0016_vaccinepackagedisease_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinepackage',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
