# Generated by Django 5.2.6 on 2025-10-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0017_vaccinepackage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='deferral_note',
            field=models.TextField(blank=True, null=True, verbose_name='Hoãn tiêm chủng'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='efficacy_text',
            field=models.TextField(blank=True, null=True, verbose_name='Hiệu quả bảo vệ'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='pregnancy_note',
            field=models.TextField(blank=True, null=True, verbose_name='Lưu ý với phụ nữ mang thai'),
        ),
    ]
