# Generated by Django 5.2.6 on 2025-10-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0018_vaccine_deferral_note_vaccine_efficacy_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='other_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Các chú ý khác'),
        ),
    ]
