# Generated by Django 5.2.6 on 2025-10-14 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_appointment_options_and_more'),
        ('vaccines', '0020_booking_member_bookingitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.familymember', verbose_name='Người tiêm'),
        ),
    ]
