# Generated by Django 5.2.6 on 2025-10-15 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0021_alter_booking_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingitem',
            options={'verbose_name': 'Mục vắc xin', 'verbose_name_plural': 'Danh sách mục vắc xin'},
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vaccines.booking', verbose_name='Đơn đặt hẹn'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số liều'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccines.vaccine', verbose_name='Vắc xin'),
        ),
    ]
