# Generated by Django 5.2.6 on 2025-10-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0022_alter_bookingitem_options_alter_bookingitem_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='appointment_time',
        ),
    ]
