# Generated by Django 5.2.6 on 2025-10-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0023_remove_booking_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=20, verbose_name='Ngưỡng cảnh báo tồn thấp'),
        ),
    ]
