# Generated by Django 5.2.6 on 2025-11-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0027_remove_booking_stubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Icon (emoji hoặc mã unicode)'),
        ),
    ]
