# Generated by Django 5.2.6 on 2025-11-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0028_disease_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='icon',
        ),
    ]
