# Generated by Django 5.2.6 on 2025-12-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0029_remove_disease_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='doses_required',
        ),
        migrations.RemoveField(
            model_name='vaccine',
            name='interval_days',
        ),
        migrations.AddField(
            model_name='disease',
            name='doses_required',
            field=models.IntegerField(default=1, verbose_name='Phác đồ điều trị'),
        ),
        migrations.AddField(
            model_name='disease',
            name='interval_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Khoảng cách giữa các mũi tiêm (ngày)'),
        ),
    ]
