# Generated by Django 5.2.6 on 2025-12-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0030_remove_vaccine_doses_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='min_age',
            field=models.IntegerField(blank=True, help_text='VD: 0 hoặc 1', null=True, verbose_name='Tuổi nhỏ nhất'),
        ),
    ]
