# Generated by Django 5.2.6 on 2025-11-11 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgecategory',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='knowledgecategory',
            name='description',
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_knowledge_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='knowledges.knowledgecategory'),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='disease',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='vaccine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgearticle',
            name='visibility',
            field=models.CharField(choices=[('normal', 'Bình thường'), ('featured', 'Nổi bật / thẻ lớn'), ('multimedia', 'Multimedia / video / infographic')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgecategory',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
