# Generated by Django 5.2.6 on 2025-10-09 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinationrecord',
            old_name='reaction',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='dose_number',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='injection_date',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='member',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='vaccine',
        ),
        migrations.AddField(
            model_name='familymember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='records.familymember'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='next_dose_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vaccination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vaccine_lot',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Vợ', 'Vợ'), ('Chồng', 'Chồng'), ('Con trai', 'Con trai'), ('Con gái', 'Con gái'), ('Bố', 'Bố'), ('Mẹ', 'Mẹ'), ('Ông nội', 'Ông nội'), ('Bà nội', 'Bà nội'), ('Ông ngoại', 'Ông ngoại'), ('Bà ngoại', 'Bà ngoại'), ('Bạn bè', 'Bạn bè'), ('Khác', 'Khác')], default='Khác', max_length=50),
        ),
    ]
