# Generated by Django 5.2.6 on 2025-10-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_reaction_vaccinationrecord_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Bản thân', 'Bản thân'), ('Vợ', 'Vợ'), ('Chồng', 'Chồng'), ('Con trai', 'Con trai'), ('Con gái', 'Con gái'), ('Bố', 'Bố'), ('Mẹ', 'Mẹ'), ('Ông nội', 'Ông nội'), ('Bà nội', 'Bà nội'), ('Ông ngoại', 'Ông ngoại'), ('Bà ngoại', 'Bà ngoại'), ('Bạn bè', 'Bạn bè'), ('Khác', 'Khác')], default='Khác', max_length=50),
        ),
    ]
