# Generated by Django 5.2.6 on 2025-10-09 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_familymember_relation'),
        ('vaccines', '0011_alter_booking_options_alter_disease_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_self',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccines.disease'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='dose_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
