# Generated by Django 5.2.6 on 2025-10-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_familymember_is_self_vaccinationrecord_disease_and_more'),
        ('vaccines', '0012_remove_vaccine_age_group_vaccine_age_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaccines.vaccine'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='dose_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
