# Generated by Django 5.2.6 on 2025-10-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_vaccinationrecord_vaccine_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date'], 'verbose_name': 'Lịch hẹn tiêm', 'verbose_name_plural': 'Danh sách lịch hẹn tiêm'},
        ),
        migrations.AlterModelOptions(
            name='vaccinationrecord',
            options={'ordering': ['-vaccination_date', '-id'], 'verbose_name': 'Mũi tiêm', 'verbose_name_plural': 'Lịch sử tiêm chủng'},
        ),
    ]
