# Generated by Django 5.2.6 on 2025-10-15 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_appointment_options_and_more'),
        ('vaccines', '0022_alter_bookingitem_options_alter_bookingitem_booking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Lịch hẹn tiêm (Booking)',
                'verbose_name_plural': 'Danh sách lịch hẹn tiêm (Booking)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vaccines.booking',),
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thành viên gia đình', 'verbose_name_plural': 'Danh sách thành viên gia đình'},
        ),
        migrations.AlterField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], default='other', max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='is_self',
            field=models.BooleanField(default=False, verbose_name='Là bản thân'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên gọi'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Bản thân', 'Bản thân'), ('Vợ', 'Vợ'), ('Chồng', 'Chồng'), ('Con trai', 'Con trai'), ('Con gái', 'Con gái'), ('Bố', 'Bố'), ('Mẹ', 'Mẹ'), ('Ông nội', 'Ông nội'), ('Bà nội', 'Bà nội'), ('Ông ngoại', 'Ông ngoại'), ('Bà ngoại', 'Bà ngoại'), ('Bạn bè', 'Bạn bè'), ('Khác', 'Khác')], default='Khác', max_length=50, verbose_name='Mối quan hệ'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccines.disease', verbose_name='Bệnh'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='dose_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mũi số'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='records.familymember', verbose_name='Thành viên'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='next_dose_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày hẹn mũi tiếp theo'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccination_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày tiêm'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vaccines.vaccine', verbose_name='Vắc xin'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccine_lot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lô vắc xin'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên vắc xin (tự nhập)'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
