# Generated by Django 5.2.6 on 2025-10-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_bookingproxy_alter_familymember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingproxy',
            options={'verbose_name': 'Lịch hẹn tiêm (Booking)', 'verbose_name_plural': 'Danh sách lịch hẹn tiêm '},
        ),
    ]
