# Generated by Django 5.2.6 on 2025-10-23 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_booking_id_alter_bookingitem_id'),
        ('vaccines', '0027_remove_booking_stubs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='source_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='records.booking'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'appointment_date'], name='vaccines_bo_status_122042_idx'),
        ),
    ]
