# Generated by Django 5.2.6 on 2025-11-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_customernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernotification',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
