# Generated by Django 5.2.6 on 2025-11-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_customernotification_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('audience', models.CharField(choices=[('upcoming', 'Lịch hẹn sắp tới'), ('nextdose', 'Mũi tiếp theo'), ('overdue', 'Trễ hẹn')], max_length=20)),
                ('days_before', models.IntegerField(blank=True, null=True)),
                ('next_dose_days', models.IntegerField(blank=True, null=True)),
                ('title_tpl', models.CharField(max_length=255)),
                ('message_tpl', models.TextField()),
                ('channels', models.JSONField(blank=True, default=dict)),
                ('run_hour', models.IntegerField(default=8)),
                ('run_minute', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
