# Generated by Django 5.2.6 on 2025-12-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_notificationrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationrule',
            options={'verbose_name': 'Nhắc lịch tự động', 'verbose_name_plural': 'Nhắc lịch tự động'},
        ),
        migrations.AddField(
            model_name='familymember',
            name='chronic_note',
            field=models.TextField(blank=True, null=True, verbose_name='Bệnh nền / tiền sử bệnh'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang kích hoạt'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='last_run_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày chạy gần nhất'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='run_hour',
            field=models.IntegerField(default=0, verbose_name='Giờ chạy'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='run_minute',
            field=models.IntegerField(default=0, verbose_name='Phút chạy'),
        ),
    ]
