# Generated by Django 5.2.6 on 2025-12-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_alter_notificationrule_options_and_more'),
        ('vaccines', '0031_alter_vaccine_min_age'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vaccinationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('disease__isnull', False), ('next_dose_date__isnull', False), ('vaccination_date__isnull', True)), fields=('family_member', 'disease', 'next_dose_date'), name='uniq_planned_dose_per_day_by_disease'),
        ),
    ]
