# Generated by Django 5.2.6 on 2025-12-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_vaccinationrecord_uniq_planned_dose_per_day_by_disease'),
        ('vaccines', '0031_alter_vaccine_min_age'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vaccinationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('disease__isnull', False), ('vaccination_date__isnull', False)), fields=('family_member', 'disease', 'vaccination_date'), name='uniq_completed_dose_per_day_by_disease'),
        ),
    ]
