# Generated by Django 5.2.6 on 2025-12-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_vaccinationrecord_uniq_completed_dose_per_day_by_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
