# Generated by Django 5.2.6 on 2025-12-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_vaccinationrecord_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
